trigger:
  - main

pool:
  name: AMIT7AKR  # Change if you use a different self-hosted agent pool name

variables:
  SNYK_TOKEN: $(SNYK_TOKEN)  # Set this securely in Azure DevOps pipeline variables

steps:

# Step 1: Checkout code
- checkout: self

# Step 2: Install Snyk CLI (Windows)
- task: CmdLine@2
  displayName: 'Install Snyk CLI (Windows)'
  inputs:
    script: |
      curl -L https://static.snyk.io/cli/latest/snyk-win.exe -o snyk.exe
      mkdir %USERPROFILE%\snyk
      move snyk.exe %USERPROFILE%\snyk\snyk.exe
      echo ##vso[task.setvariable variable=SNYK_PATH]%USERPROFILE%\snyk

# Step 3: Verify Snyk installation
- task: CmdLine@2
  displayName: 'Verify Snyk CLI'
  inputs:
    script: |
      set PATH=%SNYK_PATH%;%PATH%
      %SNYK_PATH%\snyk.exe --version

# Step 4: Authenticate with Snyk
- task: CmdLine@2
  displayName: 'Authenticate Snyk'
  inputs:
    script: |
      set PATH=%SNYK_PATH%;%PATH%
      %SNYK_PATH%\snyk.exe auth %SNYK_TOKEN%

# Step 5: Run Snyk test on all supported projects
- task: CmdLine@2
  displayName: 'Run Snyk Test'
  inputs:
    script: |
      set PATH=%SNYK_PATH%;%PATH%
      %SNYK_PATH%\snyk.exe test --all-projects || echo "⚠️ Issues found by Snyk test"

# Step 6: Send project snapshot to Snyk dashboard
- task: CmdLine@2
  displayName: 'Send Project to Snyk Monitor'
  inputs:
    script: |
      set PATH=%SNYK_PATH%;%PATH%
      %SNYK_PATH%\snyk.exe monitor --all-projects || echo "⚠️ Snyk monitor failed"
